# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Package into node binary

on:
  release:
    types: [created]

jobs:
  publish-pkg:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout src
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dev
        shell: bash
        run: |
          npm install --dev

      - name: Install pkg
        shell: bash
        run: |
          npm install -g pkg@5.8.1
  
      - name: Build src
        shell: bash
        run: |
          npm run build

      - name: Build pkg 
        shell: bash
        run: |
          npm run pkg

      - name: Release pkg
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/push-node-alpine-arm64
            ./dist/push-node-alpine-x64
            ./dist/push-node-linux-arm64
            ./dist/push-node-linux-x64
            ./dist/push-node-macos-arm64
            ./dist/push-node-macos-x64
